-- Run this entire file in Supabase SQL Editor.
create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 username text unique not null,
 full_name text,
 created_at timestamptz default now()
);
create table if not exists public.messages (
 id bigint generated by default as identity primary key,
 sender_id uuid not null references auth.users(id) on delete cascade,
 receiver_id uuid not null references auth.users(id) on delete cascade,
 body text not null check (char_length(body) <= 2000),
 created_at timestamptz default now()
);
alter table public.profiles enable row level security;
alter table public.messages enable row level security;
create policy "profiles readable by signed in users" on public.profiles for select to authenticated using (true);
create policy "users create own profile" on public.profiles for insert to authenticated with check (auth.uid()=id);
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid()=id);
create policy "chat participants can read" on public.messages for select to authenticated using (auth.uid()=sender_id or auth.uid()=receiver_id);
create policy "users send messages" on public.messages for insert to authenticated with check (auth.uid()=sender_id);
alter table public.messages replica identity full;
alter publication supabase_realtime add table public.messages;
